---
- name: Utilities
  hosts: localhost

  tasks:
    - name: Update apt cache
      become: yes
      when: ansible_os_family == 'Debian'
      apt:
        update_cache: yes

    - name: Install utilities
      become: yes
      apt:
        state: present
        name:
          - vim
          - fzf
          - tmux
          - ripgrep

    - name: Download tmux plugin manager
      git:
        depth: 1
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "~/.tmux/plugins/tpm"
