---
- name: Install ZSH, Oh My ZSH and Spaceship
  hosts: localhost

  tasks:
    - name: Install zoxide
      become: yes
      package:
        name: zoxide
        state: present

    - name: Install ZSH
      become: yes
      package:
        name: zsh
        state: present

    - name: Ensure ZSH is the default shell
      become: yes
      command: 'chsh -s /bin/zsh {{ ansible_user }}'

    - name: Download Oh My Zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: ./install_ohmyzsh.sh

    - name: Run Oh My Zsh installation script
      command: sh ./install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"

    - name: Install spaceship prompt
      ansible.builtin.git:
        depth: 1
        repo: "https://github.com/spaceship-prompt/spaceship-prompt.git"
        dest: "$ZSH/themes/spaceship-prompt"
      environment:
        ZSH: "/home/{{ ansible_user }}/.oh-my-zsh"

    - name: Symlink to theme repository
      command: ln -fs "$ZSH/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH/themes/spaceship.zsh-theme"
      environment:
        ZSH: "/home/{{ ansible_user }}/.oh-my-zsh"

    - name: Install oh-my-zsh autosuggestion plugin
      ansible.builtin.git:
        depth: 1
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: "$ZSH/plugins/zsh-autosuggestions"
      environment:
        ZSH: "/home/{{ ansible_user }}/.oh-my-zsh"

    - name: Download my .zshrc
      get_url:
        url: https://raw.githubusercontent.com/gabrielmusskopf/dotfiles/main/.zshrc
        dest: '/home/{{ ansible_user }}/.zshrc'

    - name: Download my .spaceshiprc.zsh
      get_url:
        url: https://raw.githubusercontent.com/gabrielmusskopf/dotfiles/main/.spaceshiprc.zsh
        dest: '/home/{{ ansible_user }}/.spaceshiprc.zsh'
