---
- name: Install ZSH, Oh My ZSH and Spaceship
  hosts: localhost

  tasks:
    - name: Install binaries
      become: yes
      apt:
        pkg:
          - zoxide
          - zsh
        state: present

    - name: Ensure ZSH is the default shell
      become: yes
      command: 'chsh -s /bin/zsh {{ ansible_user }}'

    - name: Download Oh My Zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: install_ohmyzsh.sh

    - name: Run Oh My Zsh installation script
      command: sh ./install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"

    - name: Clear Oh My Zsh installation script
      file:
        path: install_ohmyzsh.sh
        state: absent

    - name: Configure plugins
      block:
        - debug: msg="ZSH directory = {{ ansible_env.ZSH }}"

        - name: Install spaceship prompt
          ansible.builtin.git:
            depth: 1
            repo: "https://github.com/spaceship-prompt/spaceship-prompt.git"
            dest: "$ZSH/themes/spaceship-prompt"

        - name: Symlink to theme repository
          command: ln -fs "$ZSH/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH/themes/spaceship.zsh-theme"

        - name: Install autosuggestion plugin
          git:
            depth: 1
            repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
            dest: "$ZSH/plugins/zsh-autosuggestions"

        - name: Install zsh-syntax-highlighting plugin
          git:
            depth: 1
            repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
            dest: "$ZSH/plugins/zsh-syntax-highlighting"

      environment:
        ZSH: "/home/{{ ansible_user }}/.oh-my-zsh"
