---
- name: Install JetBrains font
  hosts: localhost
  become: yes
  vars:
    nerd_font_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip"
    font_tmp_dir: "/tmp/nerd-font"
    font_dest_dir: "/usr/local/share/fonts"

  tasks:
    - name: Create temp directory
      file:
        path: "{{ font_tmp_dir }}"
        state: directory
        mode: '0755'

    - name: Download and unarchive
      unarchive:
        src: "{{ nerd_font_url }}"
        dest: "{{ font_tmp_dir }}"
        remote_src: yes

    - name: Create font directory
      file:
        path: "{{ font_dest_dir }}"
        state: directory
        mode: '0755'

    - name: Move fonts
      shell: mv {{ font_tmp_dir }}/*.ttf "{{ font_dest_dir }}/"

    - name: Update font cache
      command: fc-cache -fv

    - name: Cleanup
      file:
        path: "{{ font_tmp_dir }}"
        state: absent
