---
- name: Install Spotify
  hosts: localhost
  become: yes

  tasks:
    - name: Download pubkey
      shell: curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg

    - name: Add repository
      shell: 'echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list'

    - name: Install
      shell: "sudo apt-get update && sudo apt-get install spotify-client"
