-- function Color(color)
--     -- color = color or "gruvbox"
--     color = color or "kanagawa"
--     vim.cmd.colorscheme(color)
--
--     vim.o.background = "dark"
--
--     local utils = require("config.utils")
--     utils.set_hl("Normal", { bg = "none" })
--     utils.set_hl("NormalFloat", { bg = "none" })
--     utils.set_hl("Whitespace", { fg = "#292d2f" })
--     utils.set_hl("LineNr", { bg = "none" })
--     --utils.set_hl("SignColumn", { bg = "none" })
-- end
--
-- Color()
